# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  hello-world:
    runs-on: self-hosted
    steps:
    - name: hello-world-docker-action
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Aditya Rahman'

  build:
    runs-on: self-hosted
    needs: hello-world
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]
    container: node:${{ matrix.node-version }}-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules/
        key: ${{ runner.os }}-build-node-${{ matrix.node-version }}
    - run: |
        npm ci
        npm run lint --if-present
        npm run build --if-present
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-${{ matrix.node-version }}
        path: dist/

#   deploy:
#     runs-on: self-hosted
#     needs: build
#     container: kudaliar032/ansible:gpg
#     env:
#       DEPLOY_KEY_PASSPHRASE: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}
#     steps:
#     - uses: actions/checkout@v2
#     - name: Download artifact
#       uses: actions/download-artifact@v2
#       with:
#         name: dist-12
#         path: dist/
#     - name: Decrypt deploy key
#       run: ./deploy/decrypt_gpg.sh deploy/deploy_key.gpg deploy/deploy_key $DEPLOY_KEY_PASSPHRASE
#     - run: chmod 600 deploy/deploy_key
#     - name: Where me
#       run: |
#         pwd
#         ls -lha
#     - name: Play ansible deploy playbook
#       run: |
#         ansible --version
#         ansible-playbook --inventory deploy/hosts --private-key deploy/deploy_key deploy/aws.yml
#       env:
#         ANSIBLE_HOST_KEY_CHECKING: 'false'
#         ANSIBLE_DEPRECATION_WARNINGS: 'false'
