# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  hello-world:
    runs-on: self-hosted
    steps:
    - name: hello-world-docker-action
      uses: kudaliar032/hello-world-docker-action@v1
      with:
        who-to-greet: 'Aditya Rahman'

  build:
    runs-on: self-hosted
    needs: hello-world
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint --if-present
    - run: npm run build --if-present
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-${{ matrix.node-version }}
        path: dist/

  deploy:
    runs-on: self-hosted
    needs: build
    env:
      DEPLOY_KEY_PASSPHRASE: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dist-10.x
    - name: Decrypt deploy key
      run: ./deploy/decrypt_gpg.sh deploy/deploy_key.gpg deploy/deploy_key $DEPLOY_KEY_PASSPHRASE
    - run: ls -lha deploy
    - name: Play ansible deploy playbook
      uses: arillso/action.playbook@master
      with:
        playbook: deploy/aws.yml
        inventory: deploy/hosts
        private_key: deploy/deploy_key
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_DEPRECATION_WARNINGS: 'false'
